"""Relaciones en el modelo notificaciones

Revision ID: 286cf2890241
Revises: 73666a78d345
Create Date: 2025-05-20 20:40:19.651346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286cf2890241'
down_revision = '73666a78d345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medico_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['medico_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('medico_id')

    # ### end Alembic commands ###
