"""Se elimina paciente_id de Notificacion y se agrega administrativo_id en Turno

Revision ID: 4052300e1224
Revises: ec8dc5549a23
Create Date: 2025-05-15 09:29:36.921095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4052300e1224'
down_revision = 'ec8dc5549a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint('notificaciones_paciente_id_fkey', type_='foreignkey')
        batch_op.drop_column('paciente_id')

    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('administrativo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['administrativo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('administrativo_id')

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paciente_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('notificaciones_paciente_id_fkey', 'pacientes', ['paciente_id'], ['id'])

    # ### end Alembic commands ###
