"""Relaciones en el modelo medico

Revision ID: 73666a78d345
Revises: 32c48884d0cb
Create Date: 2025-05-20 20:31:59.996440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73666a78d345'
down_revision = '32c48884d0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicos', schema=None) as batch_op:
        batch_op.alter_column('matricula',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['matricula'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('matricula',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
