"""Primera migración

Revision ID: ec8dc5549a23
Revises: 
Create Date: 2025-05-14 21:26:22.547759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8dc5549a23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('PACIENTE', 'MEDICO', 'ADMIN', name='tipousuario'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('administrativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nro_legajo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(), nullable=True),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nro_historia_clinica', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('PROGRAMADO', 'CANCELADO', 'REPROGRAMADO', 'ATENDIDO', 'PERDIDO', name='estadoturno'), nullable=True),
    sa.Column('reprogramaciones', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('OTORGAMIENTO', 'CANCELACION', 'REPROGRAMACION', 'CONSULTA_REALIZADA', 'PERDIDA_TURNO', name='tiponotificacion'), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('turno_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('NO_LEIDA', 'LEIDA', name='estadonotificacion'), nullable=True),
    sa.Column('origen', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificaciones')
    op.drop_table('turnos')
    op.drop_table('pacientes')
    op.drop_table('medicos')
    op.drop_table('administrativos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
